<%!
from alembic import op
import sqlalchemy as sa
%>

"""${revision} - ${down_revision}
${message}
"""

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###