import pytest

def add(a, b):
    return a + b

# all the below was generated by copilot using command pallete and
# generate unit test

    def add(a, b):
        return a + b

    def test_add_positive_numbers():
        assert add(1, 2) == 3

    def test_add_negative_numbers():
        assert add(-1, -2) == -3

    def test_add_positive_and_negative():
        assert add(1, -1) == 0

    def test_add_zero():
        assert add(0, 0) == 0

    def test_add_large_numbers():
        assert add(1000000, 2000000) == 3000000

    if __name__ == "__main__":
        pytest.main()
